print("Raj singh Rajpoot")
print("Pushkar ")
print("Pushkar ")
print("Pushkar ")
print("Pushkar ")
print("Pushkar ")
print("Pushkar ")
print("Pushkar ")
print("Pushkar ")
print("Pushkar ")
print("Pushkar ")
print("Pushkar ")
prnt("Pushkar ")
print("Pushkar ")
print("Pushkar ")
